# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baselabwatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='engineer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='librarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='baselabwatch.School'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='techsavy',
            field=models.BooleanField(default=False),
        ),
    ]
