# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baselabwatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='auth_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
