# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-23 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselabwatch', '0002_auto_20180904_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='billing',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_donation',
            field=models.IntegerField(default=0),
        ),
    ]
