# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselabwatch', '0002_auto_20170916_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='report_type',
            field=models.CharField(choices=[('bug', 'Bug'), ('question', 'Question')], max_length=10),
        ),
    ]
