# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baselabwatch', '0003_auto_20170917_0438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='name',
            new_name='short_name',
        ),
    ]
