# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselabwatch', '0004_auto_20170927_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='short_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
