# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselabwatch', '0005_auto_20170927_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
