# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselabwatch', '0006_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logger_access',
            field=models.BooleanField(default=False),
        ),
    ]
