# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baselabwatch', '0008_auto_20170927_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='signed_in',
        ),
    ]
