# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_kiosk_active'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='kiosk',
            field=models.ManyToManyField(to='registration.Kiosk'),
        ),
    ]
