# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pollquestion_kiosk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollquestion',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
