# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170910_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollchoice',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
