# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-09 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('auth_code', models.CharField(max_length=32, unique=True)),
                ('school_image', models.URLField()),
            ],
        ),
    ]
