# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 10:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0003_auto_20170909_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='associated_school', to=settings.AUTH_USER_MODEL),
        ),
    ]
