# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_kiosk'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
