# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_kiosk_poll_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires', models.DateTimeField()),
                ('billing_cycle', models.CharField(choices=[('one', 'One Time'), ('month', 'Monthly'), ('year', 'Yearly')], max_length=5)),
                ('max_student_ids', models.IntegerField()),
                ('max_kiosks', models.IntegerField()),
                ('max_logs', models.IntegerField()),
                ('student_rewards', models.BooleanField()),
                ('data_intel', models.BooleanField()),
                ('percentage_discount', models.FloatField()),
                ('numeric_discount', models.IntegerField()),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='registration.School')),
            ],
        ),
    ]
