class TitleNavBarLink extends React.Component {
    // props:
      // text: text to display for link
      // active: is this link active?
      // href: this page's url
  
    render() {
      let hrefClass = this.props.active ? "nav-link active" : "nav-link";
      return (
        <li className="nav-item">
          <a className={hrefClass} href={this.props.href}>{this.props.text}</a>
        </li>
      )
    }
  }
  
  class TitleNavBar extends React.Component {
    // props:
      // links: text array of link data (generated by django)
    render() {
      const links = this.props.links;
      let renderedLinks = Array(links.length);
      for (let i = 0; i < links.length; i++) {
        const active = links[i].name == this.props.currentApp;
        renderedLinks.push(
          <TitleNavBarLink 
            text={links[i].title} 
            href={links[i].url} 
            active={active}
            key={i} />
        );
      }
      return (
        <ul className="navbar-nav mr-auto" id="title-nav-bar-list">
          {renderedLinks}
        </ul>
      )
    }
  }
  
  class LeftNavBarLink extends React.Component {
    // Props:
      // active: should this link be active?
      // text: text for this link
      // id: id for this link
    constructor() {
      super();
    }
    render() {
      let hrefClass = this.props.active ? "nav-link active" : "nav-link";
      return (
        <li className="nav-item">
          <a className={hrefClass} onClick={() => {this.props.handleClick(this.props.id)}} href="#">{this.props.text}</a>
        </li>
      )
    }
  }
  
  class LeftNavBar extends React.Component {
    // Props:
      // links: leftBarLinks
      // handleClick: more actions passed to parent
    constructor() {
      super();
      this.state = {
        activeIndex: 0
      }
      this.handleClick = this.handleClick.bind(this);
    }  
    handleClick(id) {
      this.setState({
        activeIndex: id
      });
      this.render();
      this.props.handleClick(id);
    }
    render() {
      const links = this.props.links;
      let renderedLinks = Array(links.length);
      for (let i = 0; i < links.length; i++) { 
        const active = i === this.state.activeIndex;
        renderedLinks.push(
          <LeftNavBarLink 
            text={links[i]}
            key={i}
            id={i}
            active={active}
            handleClick={this.handleClick}
            />
        );
      }
      return (
        <ul className="nav nav-pills flex-column" id="left-nav-bar-list">
          {renderedLinks}
        </ul>
      )
    }
  }
  