# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('bug', 'Question'), ('question', 'Question')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('dealt_with', models.BooleanField(default=False)),
            ],
        ),
    ]
