# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_kiosk_poll_active'),
        ('index', '0002_userreport_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(unique=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.School')),
            ],
        ),
    ]
