# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-09 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('IN', 'Sign in'), ('OUT', 'Sign out')], max_length=3)),
                ('input_mode', models.CharField(choices=[('CARD', 'Card Scan'), ('NAME', 'Name input')], default='CARD', max_length=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poll_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.PollChoice')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('student_id', models.IntegerField(unique=True)),
                ('teacher', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, choices=[('9', 'Freshman'), ('10', 'Sophomore'), ('11', 'Junior'), ('12', 'Senior')], max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('signed_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.Student'),
        ),
    ]
