# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsession',
            name='sign_in_mode',
            field=models.CharField(choices=[('CARD', 'Card Scan'), ('NAME', 'Name input'), ('EMAL', 'Email'), ('NICK', 'Nickname input'), ('ADMI', 'Admin input')], max_length=4),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='sign_out_mode',
            field=models.CharField(blank=True, choices=[('CARD', 'Card Scan'), ('NAME', 'Name input'), ('EMAL', 'Email'), ('NICK', 'Nickname input'), ('ADMI', 'Admin input')], max_length=4),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='sign_out_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
