# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_kiosk_active'),
        ('logger', '0002_auto_20170908_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this student attends.', null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.School'),
        ),
        migrations.AlterField(
            model_name='log',
            name='input_mode',
            field=models.CharField(choices=[('CARD', 'Card Scan'), ('NAME', 'Name input'), ('EMAL', 'Email'), ('NICK', 'Nickname input'), ('ADMI', 'Admin input')], default='CARD', max_length=4),
        ),
    ]
