# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20170928_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiosk',
            name='active',
        ),
    ]
