# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_auto_20170910_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(help_text='School this student attends.', null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.School'),
        ),
    ]
