# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_auto_20170910_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, choices=[('9', 'Freshman'), ('10', 'Sophomore'), ('11', 'Junior'), ('12', 'Senior'), ('GD', 'Graduated')], max_length=2),
        ),
    ]
