# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_auto_20171008_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiosk',
            name='auth_code',
        ),
    ]
