# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_remove_kiosk_auth_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk',
            name='auth_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
