# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_auto_20170913_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('signin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_signin', to='logger.Log')),
                ('signout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_signout', to='logger.Log')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.Student')),
            ],
        ),
    ]
